<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>vision_detect_ros</name>
  <version>1.0.0</version>
  <description>Vision_detect_ros</description>
  <maintainer email="weiguo.shen@ultirobotics.com">Weiguo Shen</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>vision_interface</depend>
  <depend>vision_utils</depend>
  <depend>vision_algorithm</depend>
  <depend>opencv2</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
