#!/usr/bin/env python3
"""Prepare a new XYZ pick/place task using the maintained planner and Track-C consumer.

This is orchestration only: it does not implement IK/RRT/Servo and never authorizes
or starts real robot motion.  The generated COMMANDS.md keeps hardware steps explicit.
"""
from __future__ import annotations

import argparse
import datetime as dt
import hashlib
import json
import shutil
import subprocess


def mm_to_m(values):
    return [float(v) / 1000.0 for v in values]

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PLANNER = ROOT / "src/pick_place_coord/pick_place_coord.py"
VALIDATOR = ROOT / "src/pick_place_coord/validate_trajectory.py"
EXECUTOR = ROOT / "src/frame_calibration/robot_side/execute_servo_grasp.py"
ARM_PROFILES = ROOT / "src/arm_profiles.v1.json"


def sha256(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for block in iter(lambda: f.read(1024 * 1024), b""):
            h.update(block)
    return h.hexdigest()


def validate_xyz_task(path: Path) -> dict:
    raw = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(raw, dict) or not isinstance(raw.get("pairs"), list) or not raw["pairs"]:
        raise ValueError("task 必须包含非空 pairs 数组")
    for i, pair in enumerate(raw["pairs"], 1):
        if set(pair) < {"pick", "place"}:
            raise ValueError(f"pairs[{i}] 缺 pick/place")
        for key in ("pick", "place"):
            v = pair[key]
            if not isinstance(v, list) or len(v) != 3 or not all(isinstance(x, (int, float)) for x in v):
                raise ValueError(f"pairs[{i}].{key} 必须是 3 个数值（world XYZ, mm）")
    for i, ob in enumerate(raw.get("obstacles", []), 1):
        for key in ("center", "half"):
            v = ob.get(key)
            if not isinstance(v, list) or len(v) != 3 or not all(isinstance(x, (int, float)) for x in v):
                raise ValueError(f"obstacles[{i}].{key} 必须是 3 个数值（world XYZ, mm）")
        if any(float(x) <= 0 for x in ob["half"]):
            raise ValueError(f"obstacles[{i}].half 必须为正")
    return raw


def run(cmd: list[str], cwd: Path | None = None) -> None:
    print("+", " ".join(str(x) for x in cmd), flush=True)
    subprocess.run(cmd, cwd=cwd, check=True)


def commands_md(outdir: Path, candidate_name: str, arm: str) -> str:
    arm_id, gripper_id = (1, 2) if arm == "left" else (2, 1)
    rel = f"$HANDOFF_ROOT/{outdir.relative_to(ROOT).as_posix()}/{candidate_name}"
    return f"""# Commands for this newly planned candidate

This file was generated by `tools/new_task_pipeline.py`.  The candidate is NEW and
inherits no historical B2/B3/B4/B5 hardware qualification.

## 1. Offline validation

```bash
cd "$HANDOFF_ROOT"
python3 src/pick_place_coord/validate_trajectory.py "{rel}"
```

## 2. Track-C style dry run (no robot connection / no motion)

```bash
cd "$HANDOFF_ROOT"
XIFENG_ALLOW_REAL_MOTION=0 python3 src/frame_calibration/robot_side/execute_servo_grasp.py \\
  "{rel}" --step-deg 0.4 --period-ms 20 --speed 5 --arm-id {arm_id} --gripper-id {gripper_id}
```

## 3. Controller read-only precheck (requires current site IPs; no motion)

```bash
cd "$HANDOFF_ROOT"
XIFENG_ALLOW_REAL_MOTION=0 python3 src/frame_calibration/robot_side/execute_servo_grasp.py \\
  "{rel}" --step-deg 0.4 --period-ms 20 --speed 5 --arm-id {arm_id} --gripper-id {gripper_id} \\
  --robot-ip "$XIFENG_ROBOT_IP" --local-ip "$XIFENG_LOCAL_IP" --arm-ip "$XIFENG_ARM_IP" \\
  --controller-precheck-only --controller-precheck-report "{rel}.controller_precheck.json"
```

## 4. Real execution

Not generated as an automatic pipeline step.  Real execution remains an explicit
operator action after the new candidate, current scene, controller limits, entry path,
TCP/gripper configuration and site authorization have been reviewed.  See `robot/README.md`.

## MPC / B4 note

Do **not** rename this legacy planner output to `tabletop_pick_place_SERVO_CANDIDATE.json`.
Historical B4/B5 inputs are different SHA-bound contracts.  MPC remains an optional
control layer after a compatible candidate has been qualified; it is not part of this
XYZ planning wrapper.
"""


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--task", type=Path, required=True,
                    help="pairs+obstacles JSON; Robot world coordinates in millimetres")
    ap.add_argument("--out", type=Path, required=True, help="output directory")
    ap.add_argument("--stage", choices=("check", "plan", "validate", "prepare"), default="prepare")
    ap.add_argument("--seed", type=int, default=7)
    ap.add_argument("--arm", choices=("left", "right"), default="left")
    ap.add_argument("--python", default=sys.executable,
                    help="Python interpreter used for planner/validator (default: current Python)")
    a = ap.parse_args(argv)

    task = a.task.resolve()
    if not task.is_file():
        ap.error(f"task 不存在: {task}")
    validate_xyz_task(task)
    for required in (PLANNER, VALIDATOR, EXECUTOR, ARM_PROFILES):
        if not required.is_file():
            raise SystemExit(f"缺交接依赖: {required.relative_to(ROOT)}")

    outdir = a.out.resolve()
    try:
        outdir.relative_to(ROOT)
    except ValueError:
        raise SystemExit("--out 必须位于当前 handoff 仓库内（建议 .runtime/<name>）")
    outdir.mkdir(parents=True, exist_ok=True)
    input_copy = outdir / "input_task.json"

    # Convert user-facing mm coordinates into PyBullet metres
    # Keep original task.json untouched.
    import json

    task_data = json.loads(task.read_text(encoding="utf-8"))

    for pair in task_data["pairs"]:
        pair["pick"] = mm_to_m(pair["pick"])
        pair["place"] = mm_to_m(pair["place"])

    for obs in task_data.get("obstacles", []):
        if "center" in obs:
            obs["center"] = mm_to_m(obs["center"])
        if "half" in obs:
            obs["half"] = mm_to_m(obs["half"])

    task_data["unit_internal"] = {
        "position": "m",
        "orientation": "deg"
    }

    input_copy.write_text(
        json.dumps(task_data, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8"
    )
    candidate = outdir / "planned_candidate.json"
    report = outdir / "pipeline_report.json"

    if a.stage in ("plan", "prepare"):
        run([a.python, "-B", str(PLANNER), "--task", str(input_copy),
             "--seed", str(a.seed), "--arm", a.arm, "--direct", "--out", str(candidate)],
            cwd=ROOT / "src/pick_place_coord")
    if a.stage == "validate":
        if not candidate.is_file():
            raise SystemExit(f"缺 {candidate}; 先 --stage plan 或直接 --stage prepare")
        run([a.python, str(VALIDATOR), str(candidate)] + (["--candidate"] if a.arm == "right" else []), cwd=ROOT)

    payload = {
        "schema_version": "new_task_pipeline_report.v1",
        "created": dt.datetime.now().isoformat(timespec="seconds"),
        "stage": a.stage,
        "arm": a.arm,
        "seed": a.seed,
        "input_task": str(input_copy.relative_to(ROOT)),
        "input_task_sha256": sha256(input_copy),
        "planner": str(PLANNER.relative_to(ROOT)),
        "planner_sha256": sha256(PLANNER),
        "validator": str(VALIDATOR.relative_to(ROOT)),
        "validator_sha256": sha256(VALIDATOR),
        "executor": str(EXECUTOR.relative_to(ROOT)),
        "executor_sha256": sha256(EXECUTOR),
        "candidate": str(candidate.relative_to(ROOT)) if candidate.is_file() else None,
        "candidate_sha256": sha256(candidate) if candidate.is_file() else None,
        "real_motion_authorized": False,
        "note": "Orchestration only; historical hardware qualification is not inherited.",
    }
    report.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    (outdir / "COMMANDS.md").write_text(commands_md(outdir, candidate.name, a.arm), encoding="utf-8")
    print(json.dumps({"status": "PASS", "stage": a.stage,
                      "out": str(outdir), "candidate": payload["candidate"],
                      "real_motion_authorized": False}, ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
